a = input('Digite Algo:')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaço?', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É Alfanumerico', a.isalnum())
print('Está em mausculas?', a.isupper())
print('Está em minuscula?', a.islower())
print('Está capitalizada?', a.istitle())
